### ISSUE TITLE
Unable to the video player component in touch UI for aem 6.4

### ISSUE THREAD

**Issue by nicole-cordeiro** [coresecure/Adobe-AEM-Brightcove-Connector#25]
The dialog just keeps loading in touch UI

**Comment by pablo-kropilnicki** [comment]
Hey Nicole,

We are not currently supporting 6.4 as highlighted here : https://support.brightcove.com/getting-started-brightcove-video-connect-adobe-experience-manager . 

Stay tuned for 6.4 compatible release.

**Comment by nicole-cordeiro** [comment]
Hey Pablo,

Thank you for the updates but do we have a touch ui version for the brightcove video player component for the older versions?

**Comment by pablo-kropilnicki** [comment]
Indeed, you can create an configure the touch UI brightcove component as shown here: https://support.brightcove.com/adobe-aem-brightcove-connector-using-connector
