### ISSUE TITLE
AEM 6.4 Compatibility?

### ISSUE THREAD

**Issue by sixtrojans** [coresecure/Adobe-AEM-Brightcove-Connector#27]
Has the connector been tested against AEM 6.4 for compatibility, and will the connector be ready for AEM 6.5? (For example, AEM customers are being instructed to move the location of AEM tags  from /etc to /content to prepare for AEM 6.5 next spring, can the connector handle changes like this?)

**Comment by pablo-kropilnicki** [comment]
Hey @sixtrojans, 6.4 compatibility testing and development has been on the roadmap and is currently underway. There are features also in the works to keep the connector inline with Brightcove's new interactive video capabilities. As for AEM 6.5, will be dependent on 6.4 release, which should be prior to the end of this year. Next spring would be ideal, however, there are no projected dates as of this time. Full support of Brightcove / AEM's media tagging functionality will be kept.

**Comment by rajeevyadav2** [comment]
Hi Team,

Want to follow up if connector has been tested with 6.4? 

Thanks,
Rajeev

**Comment by ekaldany-bc** [comment]
Hello, yes we have tested it. It has not been officially updated as compatible with 6.4 but we anticipate it shortly. Thank you.
