### ISSUE TITLE
SEO support

### ISSUE THREAD

**Issue by ahmed-musallam** [coresecure/Adobe-AEM-Brightcove-Connector#29]
Hello,

Does this connector generate the video SEO schema? weather be JSON-LD or Microdata per: https://schema.org/VideoObject?

Are there any plans to make that happen?

**Comment by pablo-kropilnicki** [comment]
Hey @ahmed-musallam , this is not a feature as of this time and there is no current plan to support this.

However, thanks for suggesting it, will be looked into.
