### ISSUE TITLE
URI for brightcove replication agent

### ISSUE THREAD

**Issue by cteja1** [coresecure/Adobe-AEM-Brightcove-Connector#31]
what is the URI for brightcove replication agent, currently it is brightcove://localhost:4503/bin/receive
Do i need to replace localhost:4503 with the environment specific publisher URI

How does the replication works here, how vidoes are getting synchronized to brightcove

**Comment by pablo-kropilnicki** [comment]
Hey @cteja1, the way that the brightcove replication agent works is not like the regular replication agents.

Videos get synchronized to brightcove and back through the activation of the asset in the damadmin, however, this does not mean there is an asset getting sent over. 

There is no change required to the replication agent url, check brightcove logs to make sure the replication event is triggering the video update. Works as installed OOTB
