### ISSUE TITLE
AEM 6.4 and 6.5 Support

### ISSUE THREAD

**Issue by jenslauterbach** [coresecure/Adobe-AEM-Brightcove-Connector#32]
According to the README file the connector supports AEM 6.2 and 6.3. Is there support planned for 6.4 and 6.5?

Have there been any tests performed on the newer versions of AEM?

**Comment by ekaldany-bc** [comment]
Hi Jens, it is currently tested through 6.4, no current plans for 6.5 at the moment.

**Comment by pablo-kropilnicki** [comment]
Closed for now - Will reopen once testing for 6.4 is adjourned.

**Comment by prestoncrawford** [comment]
Does this mean 6.5 won't be supported or isn't currently being planned yet?

**Comment by ekaldany-bc** [comment]
It will be supported by does not have a date for support as yet.
